EmployerSignUp/urls.py
from django.urls import path
from . import views


app_name='EmployerSignUp'
urlpatterns = [
    path("", views.index, name="index"),
]

EmployerSingIn/urls.py
from django.urls import path
from . import views

app_name = "EmployerSignIn"
urlpatterns = [
    path("", views.index, name="index")
]

HandyTools/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('LandingPage.urls')),
    path('ESignIn/', include('EmployerSingIn.urls')),
    path("ESignUp/", include('EmployerSignUp.urls')),
    path("Logins/", include('Logins.urls')),
]

LandingPage/urls.py
from django.urls import path
from . import views

app_name="LandingPage"
urlpatterns = [
    path("", views.LandingPage, name="LandingPage"),
]

Logins/urls.py
from django.urls import path
from . import views

app_name="Logins"
urlpatterns = [
    path("", views.index, name='index')
]

EmployerSignUp/models.py
from django.db import models

# Create your models here.

EmployerSingIn/models.py
from django.db import models

# Create your models here.

LandingPage/models.py
from django.db import models

# Create your models here.

Logins/models.py
from django.db import models

# Create your models here.

EmployerSignUp/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, "EmployerSignUp/index.html")

EmployerSingIn/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "EmployerSingIn/index.html")

LandingPage/views.py
from django.shortcuts import render

# Create your views here.

def LandingPage(request):
    return render(request, "LandingPage/Landing.html")

Logins/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, "Logins/index.html")

EmployerSignUp/templates/EmployerSignUp/index.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Sign-up</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="{% static 'EmployerSignIn/style.css' %}" rel="stylesheet" />
    </head>
    <body>
       <div class="container">
            <div>
                <h2>Sign Up<h2>
            </div>
            <p>Sign Up For your Employer account</p>

            <form>
                <lable>First Name</lable>
                <div>
                    <input placeholder='Enter name'>
                </div>

                <lable>Last Name</lable>
                <div>
                    <input placeholder='Last name'>
                </div>

                <lable for='email'>Email</lable>
                <div class="email">
                    <input id='email' type=email placeholder='Enter Email' required>
                </div>

                <lable for='password'>Password</lable>
                <div class"password">
                    <input id='password' type=password placeholder='Enter password' required>
                </div>

                <lable for='Re-password'>Password Again</lable>
                <div class"Re-password">
                    <input id='Re-password' type=password placeholder='RE-Enter password' required>
                </div>

                <button>Sign Up</button>
                <p>Already have a account? <a href="{% url 'EmployerSignIn:index' %}">Sign In</a>
              
            </form>
       </div>         
    </body>
</html>

EmployerSingIn/templates/EmployerSingIn/index.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>SignIn</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="{% static 'EmployerSignIn/style.css' %}" rel="stylesheet" />
    </head>
    <body>
       <div class="container">
            <div>
                <h2>Sign In<h2>
            </div>
            <p>Sign in to your Employer account</p>

            <form>
                <lable for='email'>Email</lable>
                <div class="email">
                    <input id='email' type=email placeholder='Enter Email' required>
                </div>

                <lable for='password'>Password</lable>
                <div class"password">
                    <input id='password' type=password placeholder='Enter password' required>
                </div>

                

                <button>Sign In</button>
                <p>Dont have a account? <a href="{% url 'EmployerSignUp:index' %}">Sign Up</a>
            </form>
       </div>         
    </body>
</html>

LandingPage/templates/LandingPage/Landing.html
{% extends 'LandingPage/layout.html' %}
{% load static %}

{% block title %}Landing{% endblock %}

{% block content %}
<div class="header">
    <h2>Handy Tools</h2>
    <div class="nav-container">
      <nav>
        <ul>
          <li><a href="{% url 'EmployerSignIn:index' %}">Create/Login</a></li>
          <li><a href="#">Contacts</a></li>
        </ul>
      </nav>
    </div>
  </div>

  <div class="Heading"> 
    <h4>Looking For Servies?</h4>
  </div>

  <div class="GetStarted-Button">
    <button><a href="{% url 'Logins:index' %}"> Get Started </a> </button>
  </div>

  <div class="Pagination">
    <div class="PreviousSection">
      <
    </div>
  
    <div class="pagination-section">
      <section>image<section>
    </div>
  
    <div class="NextSection">
      <
    </div>
  </div>
  
  
    <footer>
        <p>&copy; 2024 Handy Tools. All rights reserved.</p>
      </footer>
        
{% endblock %}

LandingPage/templates/LandingPage/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <link href="{% static 'LandingPage/style.css' %}" rel="stylesheet" />
    <title>{% block title %}Page Title{% endblock %}</title>
  </head>
  <body>
    {% block content %}{% endblock %}
  </body>
</html>

Logins/templates/Logins/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'Logins/style.css' %}" rel="stylesheet" />
    <title>Accounts</title>
</head>
<body>

    <div class="container">
        <p>Sign in As..</p>
        <div class="col1">
            <button><a href="{% url 'EmployerSignIn:index'%}">Sign in as Employer</a> </button>
        </div>

        <div class="col2">
            <button> <a href"{% url 'EmployerSignIn:index' %}">Sign in as individual</a> </button>
        </div>
    </div>
</body>
</html>